update=3/10/2017 3:51:38 PM
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=../../Pcb
[eeschema/libraries]
LibName1=CA6
LibName2=power
LibName3=device
LibName4=transistors
LibName5=conn
LibName6=linear
LibName7=regul
LibName8=74xx
LibName9=cmos4000
LibName10=adc-dac
LibName11=memory
LibName12=xilinx
LibName13=microcontrollers
LibName14=dsp
LibName15=microchip
LibName16=analog_switches
LibName17=motorola
LibName18=texas
LibName19=intel
LibName20=audio
LibName21=interface
LibName22=digital-audio
LibName23=philips
LibName24=display
LibName25=cypress
LibName26=siliconi
LibName27=opto
LibName28=atmel
LibName29=contrib
LibName30=valves
LibName31=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/w_rtx
LibName32=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-ESP8266-master/ESP8266
LibName33=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/74xgxx
LibName34=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/74xx
LibName35=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/ac-dc
LibName36=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/actel
LibName37=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/adc-dac
LibName38=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/allegro
LibName39=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/Altera
LibName40=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/analog_devices
LibName41=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/analog_switches
LibName42=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/atmel
LibName43=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/audio
LibName44=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/battery_management
LibName45=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/bbd
LibName46=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/bosch
LibName47=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/brooktre
LibName48=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/cmos_ieee
LibName49=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/cmos4000
LibName50=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/conn
LibName51=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/contrib
LibName52=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/cypress
LibName53=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/dc-dc
LibName54=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/device
LibName55=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/digital-audio
LibName56=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/diode
LibName57=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/display
LibName58=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/dsp
LibName59=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/elec-unifil
LibName60=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/ESD_Protection
LibName61=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/ftdi
LibName62=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/gennum
LibName63=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/graphic
LibName64=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/hc11
LibName65=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/intel
LibName66=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/interface
LibName67=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/ir
LibName68=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/Lattice
LibName69=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/linear
LibName70=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/logo
LibName71=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/maxim
LibName72=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/mechanical
LibName73=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/memory
LibName74=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/microchip
LibName75=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/microchip_dspic33dsc
LibName76=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/microchip_pic10mcu
LibName77=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/microchip_pic12mcu
LibName78=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/microchip_pic16mcu
LibName79=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/microchip_pic18mcu
LibName80=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/microchip_pic32mcu
LibName81=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/microcontrollers
LibName82=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/motor_drivers
LibName83=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/motorola
LibName84=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/motors
LibName85=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/msp430
LibName86=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/nordicsemi
LibName87=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/NXP
LibName88=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/nxp_1
LibName89=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/nxp_armmcu
LibName90=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/onsemi
LibName91=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/opto
LibName92=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/Oscillators
LibName93=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/philips
LibName94=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/power
LibName95=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/Power_Management
LibName96=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/powerint
LibName97=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/pspice
LibName98=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/references
LibName99=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/regul
LibName100=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/relays
LibName101=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/rfcom
LibName102=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/sensors
LibName103=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/silabs
LibName104=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/siliconi
LibName105=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/stm8
LibName106=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/stm32
LibName107=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/supertex
LibName108=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/switches
LibName109=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/texas
LibName110=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/transf
LibName111=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/transistors
LibName112=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/triac_thyristor
LibName113=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/ttl_ieee
LibName114=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/valves
LibName115=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/video
LibName116=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/wiznet
LibName117=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/Worldsemi
LibName118=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/Xicor
LibName119=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/xilinx
LibName120=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/zetex
LibName121=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/kicad-library-master/library/Zilog
LibName122=F:/Users/dlenardon/Documents/electronics/KiCAD libraries/Peter_Polidoro_components
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
RptD_X=0
RptD_Y=100
RptLab=1
LabSize=60
