update=12/19/2017 8:35:08 AM
version=1
last_client=kicad
[general]
version=1
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[pcbnew/libraries]
LibName1=CA6
LibName2=capacitors
LibName3=connect
LibName4=connectors_molex_serial_53047-A123
LibName5=dip_sockets
LibName6=discret
LibName7=display
LibName8=divers
LibName9=inductors
LibName10=led
LibName11=libcms
LibName12=pin_array
LibName13=powerint
LibName14=smd_capacitors
LibName15=smd_resistors
LibName16=sockets
LibName17=valves
LibDir=
[cvpcb]
version=1
NetIExt=net
[cvpcb/libraries]
EquName1=devcms
[eeschema]
version=1
LibDir=../../../Pcb
[eeschema/libraries]
LibName1=CA6
LibName2=C:/Program Files/KiCad/share/kicad/library/74xx
LibName3=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName4=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName5=C:/Program Files/KiCad/share/kicad/library/actel
LibName6=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName7=C:/Program Files/KiCad/share/kicad/library/allegro
LibName8=C:/Program Files/KiCad/share/kicad/library/Altera
LibName9=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName10=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName11=C:/Program Files/KiCad/share/kicad/library/atmel
LibName12=C:/Program Files/KiCad/share/kicad/library/audio
LibName13=C:/Program Files/KiCad/share/kicad/library/battery_management
LibName14=C:/Program Files/KiCad/share/kicad/library/bbd
LibName15=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName16=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName17=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName18=C:/Program Files/KiCad/share/kicad/library/conn
LibName19=C:/Program Files/KiCad/share/kicad/library/contrib
LibName20=C:/Program Files/KiCad/share/kicad/library/cypress
LibName21=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName22=C:/Program Files/KiCad/share/kicad/library/device
LibName23=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName24=C:/Program Files/KiCad/share/kicad/library/diode
LibName25=C:/Program Files/KiCad/share/kicad/library/display
LibName26=C:/Program Files/KiCad/share/kicad/library/dsp
LibName27=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName28=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName29=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName30=C:/Program Files/KiCad/share/kicad/library/gennum
LibName31=C:/Program Files/KiCad/share/kicad/library/graphic
LibName32=C:/Program Files/KiCad/share/kicad/library/hc11
LibName33=C:/Program Files/KiCad/share/kicad/library/intel
LibName34=C:/Program Files/KiCad/share/kicad/library/interface
LibName35=C:/Program Files/KiCad/share/kicad/library/ir
LibName36=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName37=C:/Program Files/KiCad/share/kicad/library/linear
LibName38=C:/Program Files/KiCad/share/kicad/library/logo
LibName39=C:/Program Files/KiCad/share/kicad/library/maxim
LibName40=C:/Program Files/KiCad/share/kicad/library/mechanical
LibName41=C:/Program Files/KiCad/share/kicad/library/memory
LibName42=C:/Program Files/KiCad/share/kicad/library/microchip
LibName43=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName44=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName45=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName46=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName47=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName48=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName49=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName50=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName51=C:/Program Files/KiCad/share/kicad/library/motorola
LibName52=C:/Program Files/KiCad/share/kicad/library/motors
LibName53=C:/Program Files/KiCad/share/kicad/library/msp430
LibName54=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName55=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName56=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName57=C:/Program Files/KiCad/share/kicad/library/opto
LibName58=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName59=C:/Program Files/KiCad/share/kicad/library/philips
LibName60=C:/Program Files/KiCad/share/kicad/library/power
LibName61=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName62=C:/Program Files/KiCad/share/kicad/library/powerint
LibName63=C:/Program Files/KiCad/share/kicad/library/pspice
LibName64=C:/Program Files/KiCad/share/kicad/library/references
LibName65=C:/Program Files/KiCad/share/kicad/library/regul
LibName66=C:/Program Files/KiCad/share/kicad/library/relays
LibName67=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName68=C:/Program Files/KiCad/share/kicad/library/sensors
LibName69=C:/Program Files/KiCad/share/kicad/library/silabs
LibName70=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName71=C:/Program Files/KiCad/share/kicad/library/stm8
LibName72=C:/Program Files/KiCad/share/kicad/library/stm32
LibName73=C:/Program Files/KiCad/share/kicad/library/supertex
LibName74=C:/Program Files/KiCad/share/kicad/library/switches
LibName75=C:/Program Files/KiCad/share/kicad/library/texas
LibName76=C:/Program Files/KiCad/share/kicad/library/transf
LibName77=C:/Program Files/KiCad/share/kicad/library/transistors
LibName78=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName79=C:/Program Files/KiCad/share/kicad/library/valves
LibName80=C:/Program Files/KiCad/share/kicad/library/video
LibName81=C:/Program Files/KiCad/share/kicad/library/wiznet
LibName82=C:/Program Files/KiCad/share/kicad/library/Worldsemi
LibName83=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName84=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName85=C:/Program Files/KiCad/share/kicad/library/zetex
LibName86=C:/Program Files/KiCad/share/kicad/library/Zilog
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=Pcbnew
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
