update=9/20/2017 2:00:01 PM
version=1
last_client=kicad
[general]
version=1
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[pcbnew/libraries]
LibName1=CA6
LibName2=capacitors
LibName3=connect
LibName4=connectors_molex_serial_53047-A123
LibName5=dip_sockets
LibName6=discret
LibName7=display
LibName8=divers
LibName9=inductors
LibName10=led
LibName11=libcms
LibName12=pin_array
LibName13=powerint
LibName14=smd_capacitors
LibName15=smd_resistors
LibName16=sockets
LibName17=valves
LibDir=
[cvpcb]
version=1
NetIExt=net
[cvpcb/libraries]
EquName1=devcms
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
RptD_X=0
RptD_Y=100
RptLab=1
LabSize=60
[eeschema]
version=1
LibDir=C:/Program Files/KiCad/share/kicad/library;../../../Pcb
[eeschema/libraries]
LibName1=CA6
LibName2=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName3=C:/Program Files/KiCad/share/kicad/library/74xx
LibName4=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName5=C:/Program Files/KiCad/share/kicad/library/actel
LibName6=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName7=C:/Program Files/KiCad/share/kicad/library/allegro
LibName8=C:/Program Files/KiCad/share/kicad/library/Altera
LibName9=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName10=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName11=C:/Program Files/KiCad/share/kicad/library/atmel
LibName12=C:/Program Files/KiCad/share/kicad/library/audio
LibName13=C:/Program Files/KiCad/share/kicad/library/battery_management
LibName14=C:/Program Files/KiCad/share/kicad/library/bbd
LibName15=C:/Program Files/KiCad/share/kicad/library/bosch
LibName16=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName17=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName18=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName19=C:/Program Files/KiCad/share/kicad/library/conn
LibName20=C:/Program Files/KiCad/share/kicad/library/contrib
LibName21=C:/Program Files/KiCad/share/kicad/library/cypress
LibName22=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName23=C:/Program Files/KiCad/share/kicad/library/device
LibName24=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName25=C:/Program Files/KiCad/share/kicad/library/diode
LibName26=C:/Program Files/KiCad/share/kicad/library/display
LibName27=C:/Program Files/KiCad/share/kicad/library/dsp
LibName28=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName29=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName30=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName31=C:/Program Files/KiCad/share/kicad/library/gennum
LibName32=C:/Program Files/KiCad/share/kicad/library/graphic
LibName33=C:/Program Files/KiCad/share/kicad/library/hc11
LibName34=C:/Program Files/KiCad/share/kicad/library/intel
LibName35=C:/Program Files/KiCad/share/kicad/library/interface
LibName36=C:/Program Files/KiCad/share/kicad/library/ir
LibName37=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName38=C:/Program Files/KiCad/share/kicad/library/leds
LibName39=C:/Program Files/KiCad/share/kicad/library/linear
LibName40=C:/Program Files/KiCad/share/kicad/library/logo
LibName41=C:/Program Files/KiCad/share/kicad/library/maxim
LibName42=C:/Program Files/KiCad/share/kicad/library/mechanical
LibName43=C:/Program Files/KiCad/share/kicad/library/memory
LibName44=C:/Program Files/KiCad/share/kicad/library/microchip
LibName45=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName46=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName47=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName48=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName49=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName50=C:/Program Files/KiCad/share/kicad/library/microchip_pic24mcu
LibName51=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName52=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName53=C:/Program Files/KiCad/share/kicad/library/modules
LibName54=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName55=C:/Program Files/KiCad/share/kicad/library/motorola
LibName56=C:/Program Files/KiCad/share/kicad/library/motors
LibName57=C:/Program Files/KiCad/share/kicad/library/msp430
LibName58=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName59=C:/Program Files/KiCad/share/kicad/library/nxp
LibName60=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName61=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName62=C:/Program Files/KiCad/share/kicad/library/opto
LibName63=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName64=C:/Program Files/KiCad/share/kicad/library/philips
LibName65=C:/Program Files/KiCad/share/kicad/library/power
LibName66=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName67=C:/Program Files/KiCad/share/kicad/library/powerint
LibName68=C:/Program Files/KiCad/share/kicad/library/pspice
LibName69=C:/Program Files/KiCad/share/kicad/library/references
LibName70=C:/Program Files/KiCad/share/kicad/library/regul
LibName71=C:/Program Files/KiCad/share/kicad/library/relays
LibName72=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName73=C:/Program Files/KiCad/share/kicad/library/sensors
LibName74=C:/Program Files/KiCad/share/kicad/library/silabs
LibName75=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName76=C:/Program Files/KiCad/share/kicad/library/stm8
LibName77=C:/Program Files/KiCad/share/kicad/library/stm32
LibName78=C:/Program Files/KiCad/share/kicad/library/supertex
LibName79=C:/Program Files/KiCad/share/kicad/library/switches
LibName80=C:/Program Files/KiCad/share/kicad/library/texas
LibName81=C:/Program Files/KiCad/share/kicad/library/transf
LibName82=C:/Program Files/KiCad/share/kicad/library/transistors
LibName83=C:/Program Files/KiCad/share/kicad/library/triac_thyristor
LibName84=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName85=C:/Program Files/KiCad/share/kicad/library/valves
LibName86=C:/Program Files/KiCad/share/kicad/library/video
LibName87=C:/Program Files/KiCad/share/kicad/library/wiznet
LibName88=C:/Program Files/KiCad/share/kicad/library/Worldsemi
LibName89=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName90=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName91=C:/Program Files/KiCad/share/kicad/library/zetex
LibName92=C:/Program Files/KiCad/share/kicad/library/Zilog
